//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v14.2.0+1b21caa
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>About Page</summary>
	[PublishedModel("aboutPage")]
	public partial class AboutPage : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const string ModelTypeAlias = "aboutPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<AboutPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public AboutPage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// AboutBoxFiveImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBoxFiveImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutBoxFiveImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutBoxFiveImage");

		///<summary>
		/// AboutBoxFiveJob
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBoxFiveJob")]
		public virtual string AboutBoxFiveJob => this.Value<string>(_publishedValueFallback, "aboutBoxFiveJob");

		///<summary>
		/// AboutBoxFiveName
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBoxFiveName")]
		public virtual string AboutBoxFiveName => this.Value<string>(_publishedValueFallback, "aboutBoxFiveName");

		///<summary>
		/// AboutBoxFourImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBoxFourImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutBoxFourImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutBoxFourImage");

		///<summary>
		/// AboutBoxFourJob
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBoxFourJob")]
		public virtual string AboutBoxFourJob => this.Value<string>(_publishedValueFallback, "aboutBoxFourJob");

		///<summary>
		/// AboutBoxFourName
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBoxFourName")]
		public virtual string AboutBoxFourName => this.Value<string>(_publishedValueFallback, "aboutBoxFourName");

		///<summary>
		/// AboutBoxOneImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBoxOneImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutBoxOneImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutBoxOneImage");

		///<summary>
		/// AboutBoxOneJob
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBoxOneJob")]
		public virtual string AboutBoxOneJob => this.Value<string>(_publishedValueFallback, "aboutBoxOneJob");

		///<summary>
		/// AboutBoxOneName
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBoxOneName")]
		public virtual string AboutBoxOneName => this.Value<string>(_publishedValueFallback, "aboutBoxOneName");

		///<summary>
		/// AboutBoxSevenImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBoxSevenImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutBoxSevenImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutBoxSevenImage");

		///<summary>
		/// AboutBoxSevenJob
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBoxSevenJob")]
		public virtual string AboutBoxSevenJob => this.Value<string>(_publishedValueFallback, "aboutBoxSevenJob");

		///<summary>
		/// AboutBoxSevenName
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBoxSevenName")]
		public virtual string AboutBoxSevenName => this.Value<string>(_publishedValueFallback, "aboutBoxSevenName");

		///<summary>
		/// AboutBoxSixImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBoxSixImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutBoxSixImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutBoxSixImage");

		///<summary>
		/// AboutBoxSixName
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBoxSixName")]
		public virtual string AboutBoxSixName => this.Value<string>(_publishedValueFallback, "aboutBoxSixName");

		///<summary>
		/// AboutBoxThreeImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBoxThreeImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutBoxThreeImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutBoxThreeImage");

		///<summary>
		/// AboutBoxThreeJob
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBoxThreeJob")]
		public virtual string AboutBoxThreeJob => this.Value<string>(_publishedValueFallback, "aboutBoxThreeJob");

		///<summary>
		/// AboutBoxThreeName
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBoxThreeName")]
		public virtual string AboutBoxThreeName => this.Value<string>(_publishedValueFallback, "aboutBoxThreeName");

		///<summary>
		/// AboutBoxTwoImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBoxTwoImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutBoxTwoImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutBoxTwoImage");

		///<summary>
		/// AboutBoxTwoJob
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBoxTwoJob")]
		public virtual string AboutBoxTwoJob => this.Value<string>(_publishedValueFallback, "aboutBoxTwoJob");

		///<summary>
		/// AboutBoxTwoName
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBoxTwoName")]
		public virtual string AboutBoxTwoName => this.Value<string>(_publishedValueFallback, "aboutBoxTwoName");

		///<summary>
		/// About Expert Section Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutExpertSectionHeadline")]
		public virtual string AboutExpertSectionHeadline => this.Value<string>(_publishedValueFallback, "aboutExpertSectionHeadline");

		///<summary>
		/// About Expert Section Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutExpertSectionTitle")]
		public virtual string AboutExpertSectionTitle => this.Value<string>(_publishedValueFallback, "aboutExpertSectionTitle");

		///<summary>
		/// AboutSixJob
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSixJob")]
		public virtual string AboutSixJob => this.Value<string>(_publishedValueFallback, "aboutSixJob");

		///<summary>
		/// About Tina CEO
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutTinaCeo")]
		public virtual string AboutTinaCeo => this.Value<string>(_publishedValueFallback, "aboutTinaCeo");

		///<summary>
		/// About Tina Cursive
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutTinaCursive")]
		public virtual string AboutTinaCursive => this.Value<string>(_publishedValueFallback, "aboutTinaCursive");

		///<summary>
		/// About TinaImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutTinaImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutTinaImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutTinaImage");

		///<summary>
		/// About Tina Text Five
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutTinaTextFive")]
		public virtual string AboutTinaTextFive => this.Value<string>(_publishedValueFallback, "aboutTinaTextFive");

		///<summary>
		/// About Tina Text Four
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutTinaTextFour")]
		public virtual string AboutTinaTextFour => this.Value<string>(_publishedValueFallback, "aboutTinaTextFour");

		///<summary>
		/// About Tina Text One
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutTinaTextOne")]
		public virtual string AboutTinaTextOne => this.Value<string>(_publishedValueFallback, "aboutTinaTextOne");

		///<summary>
		/// About Tina Text Six
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutTinaTextSix")]
		public virtual string AboutTinaTextSix => this.Value<string>(_publishedValueFallback, "aboutTinaTextSix");

		///<summary>
		/// About Tina Text Three
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutTinaTextThree")]
		public virtual string AboutTinaTextThree => this.Value<string>(_publishedValueFallback, "aboutTinaTextThree");

		///<summary>
		/// About Tina Text Two
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutTinaTextTwo")]
		public virtual string AboutTinaTextTwo => this.Value<string>(_publishedValueFallback, "aboutTinaTextTwo");

		///<summary>
		/// Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitle")]
		public virtual string PageTitle => this.Value<string>(_publishedValueFallback, "pageTitle");

		///<summary>
		/// Review Section Bank
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewSectionBank")]
		public virtual string ReviewSectionBank => this.Value<string>(_publishedValueFallback, "reviewSectionBank");

		///<summary>
		/// Review Section Cursive
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewSectionCursive")]
		public virtual string ReviewSectionCursive => this.Value<string>(_publishedValueFallback, "reviewSectionCursive");

		///<summary>
		/// Review Section Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewSectionHeadline")]
		public virtual string ReviewSectionHeadline => this.Value<string>(_publishedValueFallback, "reviewSectionHeadline");

		///<summary>
		/// ReviewSectionHeadshot
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewSectionHeadshot")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ReviewSectionHeadshot => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "reviewSectionHeadshot");

		///<summary>
		/// Review Section Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewSectionName")]
		public virtual string ReviewSectionName => this.Value<string>(_publishedValueFallback, "reviewSectionName");

		///<summary>
		/// Review Section Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewSectionTitle")]
		public virtual string ReviewSectionTitle => this.Value<string>(_publishedValueFallback, "reviewSectionTitle");
	}
}
